# docker-compose up -d
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "4444:5432"
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
